elasticsearch_cluster_name: custome-cluster
elasticsearch_node_name: node1
#elasticsearch_node_data: "true"
#elasticsearch_node_master: "true"
#elasticsearch_bootstrap_memory_lock: "true"
elasticsearch_network_host: "[_local_]"
elasticsearch_http_port: 9200
#elasticsearch_discovery_zen_minimum_master_nodes: 2
#elasticsearch_discovery_zen_ping_unicast_hosts: "[\"10.0.1.2\", \"10.0.1.3\", \"10.0.1.4\"]"
elasticsearch_transport_tcp_port: 9300
#elasticsearch_http_cors_enabled: "true"
#elasticsearch_http_cors_allow_origin: "\"*\""
#elasticsearch_http_cors_allow_headers: Authorization
#elasticsearch_script_inline: "true"
#elasticsearch_script_indexed: "true"
